### ISSUE TITLE
betting crawler

### ISSUE THREAD

**Issue by dafy1978** [HaraldNordgren/betting-crawler#2]
I was wondering if i could have some help to work this betting crawler I try to install it with Kali but I can not I'm not very experienced can you please give me a hand?

**Comment by HaraldNordgren** [comment]
The crawler is a bit broken at the moment because the betting companies keep changing their websites (possibly to stop us from doing this).

`run_once.sh` is the script you want to run. It has requirements on certain programs and Python libraries. Hopefully you can figure out what you need to do.
